[programs.localnet]
nft_achievement = "7hHLaiFyPk62YEnFunGEJs9x4L3XPaZXgwEQS6UDdcjm"
identity = "3U2mqSTuSjj9QkDRT2Wy8o7DAo8iWU2iyJzHfW3W7r5f"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/dominiclee/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
