[programs.localnet]
nft_achievement = "AHQXfwGoMKFrhom1ZbkMStrFQkkZhqr31Xe7MF4bjtka"
profile = "Gs9xfexZHrVAfSNZLAfaeu8VW8vnhxEzn88PYQQxbGXT"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/dominiclee/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
